name: CI Apk

# i'm tired to set up a workflow trigger
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download ReVanced Cli
        run: wget "https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar"

      - name: Download Bilibili
#        run: wget "https://dl.hdslb.com/mobile/latest/android64/iBiliPlayer-bili.apk" -O bilibili.apk
        # use old version 8.38.0 cuz new version has lot of breaking changes
        run: wget "https://ucdl.25pp.com/fs08/2025/01/03/3/125_e40eb686b6659ac755a481b02904d48c.apk" -O bilibili.apk

      - name: Download patches
        run: wget "https://nightly.link/Ujhhgtg/BiliRoamingX/workflows/ci/main/patches.zip" -O patches.zip

      - name: Unzip patches
        run: unzip patches.zip -d patches

      - name: Rename patches
        run: mv patches/BiliRoamingX-integrations-*.apk integrations.apk && mv patches/BiliRoamingX-patches-*.jar patches.jar

      - name: Patch BiliBili
        run: java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 bilibili.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: bilibili-patched.apk
          path: './bilibili-patched.apk'

      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: 'ci'
          artifacts: './bilibili-patched.apk'
          body: 'Latest CI artifact'
